x-enviroment:
  - &env-postgres-db POSTGRES_db=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}



services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_2025_03_am_postgis'
    container_name: prge-2025-03-am-postgis-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${POSTGRES_PORT}:5432
#port pierwszzy 5433 albo 5443
    volumes:
      - postgis-prge-data:/var/lib/postgresql/data
volumes:
  postgis-prge-data:
